{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pirago.ads-helper",
    "module": "sdk-compose",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.pirago.ads-helper",
          "module": "sdk",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.12.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-compose-1.0.1.aar",
          "url": "sdk-compose-1.0.1.aar",
          "size": 8733,
          "sha512": "c6554c877ad8de9ab9c1c4a965ea15618409ffa05062490dbf350ff9b5324420c3d5049011d119f665ca598ec2eafc8ddd44b0930671261bc066e8ac0aa27284",
          "sha256": "a44b9de2ae89f2bc2cea821dc04ade8b4871357cd1f5713be12c3642de3adc17",
          "sha1": "0bb408ecbedaf4a9b44c285ca866f328ebeb485f",
          "md5": "d3f39802e8af824d4a453c7e88b9f66e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.pirago.ads-helper",
          "module": "sdk",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.12.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-compose-1.0.1.aar",
          "url": "sdk-compose-1.0.1.aar",
          "size": 8733,
          "sha512": "c6554c877ad8de9ab9c1c4a965ea15618409ffa05062490dbf350ff9b5324420c3d5049011d119f665ca598ec2eafc8ddd44b0930671261bc066e8ac0aa27284",
          "sha256": "a44b9de2ae89f2bc2cea821dc04ade8b4871357cd1f5713be12c3642de3adc17",
          "sha1": "0bb408ecbedaf4a9b44c285ca866f328ebeb485f",
          "md5": "d3f39802e8af824d4a453c7e88b9f66e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-compose-1.0.1-sources.jar",
          "url": "sdk-compose-1.0.1-sources.jar",
          "size": 1424,
          "sha512": "0f88e5e65fe4de2385ff7b3de6729dc0927c054529461c82ff0969d7b17775a2e0ecfa8467164d6e17beadee923060de44a2ae87768f60ec88fcaeed7e2c58d4",
          "sha256": "229eca076612c3c4067e843e65adff49e5648efb74724efc79f00d3465698d7c",
          "sha1": "70c7d7e4be098ac214884159b059dda73ad2ac84",
          "md5": "8cc5a4b692dffe910fb7c3229fda51cb"
        }
      ]
    }
  ]
}
