{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pirago.ads-helper",
    "module": "sdk",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.0.1.aar",
          "url": "sdk-1.0.1.aar",
          "size": 142663,
          "sha512": "d4c0ab14f65c0de0d007643d7e9da3f0813ce762ed2e4b905a0221bc3956985069c6630b79afef687539c5fda7701b225cdb5ee5b9de8c1cc2bdc02d5628dc50",
          "sha256": "90d71339b197791895b21a488a6471432f7007ba207fa2465ea9a42c35bf7591",
          "sha1": "e1bb87f57da9100416773139cc3ae1e98940c436",
          "md5": "7361468ba2f8a1ceef72c27034b8aeb5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.0.1.aar",
          "url": "sdk-1.0.1.aar",
          "size": 142663,
          "sha512": "d4c0ab14f65c0de0d007643d7e9da3f0813ce762ed2e4b905a0221bc3956985069c6630b79afef687539c5fda7701b225cdb5ee5b9de8c1cc2bdc02d5628dc50",
          "sha256": "90d71339b197791895b21a488a6471432f7007ba207fa2465ea9a42c35bf7591",
          "sha1": "e1bb87f57da9100416773139cc3ae1e98940c436",
          "md5": "7361468ba2f8a1ceef72c27034b8aeb5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-1.0.1-sources.jar",
          "url": "sdk-1.0.1-sources.jar",
          "size": 26973,
          "sha512": "920a29e6479fa3c61a59a1043b6235338db409b7c9936e62232ccf7eabb92de45d12b5b4669c33e8d939ed68480e56a64d7a21958201e8ff2233edf5dd4e0da6",
          "sha256": "cd0294e5cc126d3a9c4ff31fb8609c537544f2cdbbfbe8dd3a3200e4b43333f8",
          "sha1": "bd4d566ee693ccd2be895364a18d33300a967131",
          "md5": "5a04acd0652d7a6f8e064e00ab73f7e2"
        }
      ]
    }
  ]
}
