{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pirago.ads-helper",
    "module": "sdk",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.0.0.aar",
          "url": "sdk-1.0.0.aar",
          "size": 142661,
          "sha512": "bf2b9029a6003d56e29b09210e9bbf8597a8115c397ff1a77652c05412cb8ef1e502ab7d930f5042910e4e23d700e20d9eb25860b06b8755f492f2ab8a02794b",
          "sha256": "066d8b29fcf2c9421630477d7bf8610fc040ce1d54d243d2fd22a161bcaaca4d",
          "sha1": "d1fba8543757e5392fd654b9f69309c4c1e7a3a3",
          "md5": "136a30ef0e1593f26bd2949d12b8e78c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.0.0.aar",
          "url": "sdk-1.0.0.aar",
          "size": 142661,
          "sha512": "bf2b9029a6003d56e29b09210e9bbf8597a8115c397ff1a77652c05412cb8ef1e502ab7d930f5042910e4e23d700e20d9eb25860b06b8755f492f2ab8a02794b",
          "sha256": "066d8b29fcf2c9421630477d7bf8610fc040ce1d54d243d2fd22a161bcaaca4d",
          "sha1": "d1fba8543757e5392fd654b9f69309c4c1e7a3a3",
          "md5": "136a30ef0e1593f26bd2949d12b8e78c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-1.0.0-sources.jar",
          "url": "sdk-1.0.0-sources.jar",
          "size": 26928,
          "sha512": "eabd459a79c678fdbe3f732c983bdb54b3fe5b622a390b3c473f9322f2f63b418a683194752f4933744f2b9cb5ea4fdbe6fb6bee0147fcff4b49662bb0af9e8f",
          "sha256": "bebcefa909234a3ca7ae90d73d2124193ef8fd05c53a9a37f5f63243c92a9921",
          "sha1": "34eded88869523f2aaa7b77ea1017832b0cfa8cb",
          "md5": "855992a1800a306abdbef893985b0790"
        }
      ]
    }
  ]
}
