{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pirago.ads-helper",
    "module": "sdk",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.0.3.aar",
          "url": "sdk-1.0.3.aar",
          "size": 181504,
          "sha512": "f1ed46c8952ec91610aa1b75bdf1c81bd1a339875974759c51aa4ee8f0d8ad8cfb309da9bb6c554164e7d0ad43eaa664fc178cfb0b6946e8293cf260ec3362df",
          "sha256": "32b5b376a228d94fd051ca5d9980497e3f8fc888472f2b9bc39b0829ce8afd65",
          "sha1": "beefa481d7bb384dbf47bbd0aa7fb2fdbf175d25",
          "md5": "2b3f194d27cd95782ae3537b306fc1c0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.0.3.aar",
          "url": "sdk-1.0.3.aar",
          "size": 181504,
          "sha512": "f1ed46c8952ec91610aa1b75bdf1c81bd1a339875974759c51aa4ee8f0d8ad8cfb309da9bb6c554164e7d0ad43eaa664fc178cfb0b6946e8293cf260ec3362df",
          "sha256": "32b5b376a228d94fd051ca5d9980497e3f8fc888472f2b9bc39b0829ce8afd65",
          "sha1": "beefa481d7bb384dbf47bbd0aa7fb2fdbf175d25",
          "md5": "2b3f194d27cd95782ae3537b306fc1c0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-1.0.3-sources.jar",
          "url": "sdk-1.0.3-sources.jar",
          "size": 33234,
          "sha512": "a942d2c124e284c69b548ad0a5db4b44baa2860405384ef27ccdf0861b5dfe373b557d61bd993899c91115cff9e16839b0c19e2ba49f2e19ef62e5691df1edb4",
          "sha256": "d1db16c1209ec548ce2df46aa1d611b6d64eb8b4c2f3350d82fdd336a21e061d",
          "sha1": "26aff641789ae8cc9efd2239249d19d4d0e1a1f2",
          "md5": "d95b495038c695583e9f7c2ce9bbcc82"
        }
      ]
    }
  ]
}
