{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pirago.ads-helper",
    "module": "sdk-max",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.pirago.ads-helper",
          "module": "sdk",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "13.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-max-1.0.3.aar",
          "url": "sdk-max-1.0.3.aar",
          "size": 14115,
          "sha512": "2b4e30b90d7de851d173ce3d843092c11c9be1f077adda9c828f2a37ac70ead5ac7aa04dab586d8bd5b04dcfca4aadddca2ce3f7d9907fa9a3b33995fd1ef6bd",
          "sha256": "2a4b382bb61adb148020ca09ec0c7df025530e569ebe34f15001b0ba3230caac",
          "sha1": "db902e52082988ffaf29be85fabb00e4a3d10669",
          "md5": "a345ffa9dacceef1616a9b188d5d3da1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.pirago.ads-helper",
          "module": "sdk",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "13.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-max-1.0.3.aar",
          "url": "sdk-max-1.0.3.aar",
          "size": 14115,
          "sha512": "2b4e30b90d7de851d173ce3d843092c11c9be1f077adda9c828f2a37ac70ead5ac7aa04dab586d8bd5b04dcfca4aadddca2ce3f7d9907fa9a3b33995fd1ef6bd",
          "sha256": "2a4b382bb61adb148020ca09ec0c7df025530e569ebe34f15001b0ba3230caac",
          "sha1": "db902e52082988ffaf29be85fabb00e4a3d10669",
          "md5": "a345ffa9dacceef1616a9b188d5d3da1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-max-1.0.3-sources.jar",
          "url": "sdk-max-1.0.3-sources.jar",
          "size": 3056,
          "sha512": "94af879f3c76b5cd02fe3ad69cd45e64467774a152fe375975c5f2c609c67ecb4867bc6278e514930fac99fe3a3c70d3cbeebc95c3d243612c5c868c06aecf65",
          "sha256": "1c9b583b30fa069b6182238ad32fd82d6ec408ab332c5867a32e1b458de52f48",
          "sha1": "d5da2b4ae00497095380a7f772a77f9bd5f9c723",
          "md5": "06b428593f9aa67ea6437842e5be8888"
        }
      ]
    }
  ]
}
